### ISSUE TITLE
input without default value

### ISSUE THREAD

**Issue by AmirAghaee** [alirahimi818/livewire-persian-datepicker#1]
Hi
How can I use the input without a default value?
If the defaultDate property was not set, Input will set today's date as the default!

**Comment by alirahimi818** [comment]
Hi Amir,
You can use the "setNullInput" attribute for the default null input.
for example:

```
<x-persian-datepicker label="Date"
                            :defaultDate="$value"
                            :setNullInput="true"
                            wirePropertyName="model.date"/>
```
