### ISSUE TITLE
Cannot call a namespace ("moment").

### ISSUE THREAD

**Issue by Misagh90** [alirahimi818/livewire-persian-datepicker#4]
Hi
When I try "npm run dev" everything is ok but when I build it ("npm run build"), these errors are displayed & dates of the calendar are not shown.

> resources/js/livewire-datepicker-datepicker.js (33:24) Cannot call a namespace ("moment").
> resources/js/livewire-datepicker-datepicker.js (35:24) Cannot call a namespace ("moment").
> resources/js/livewire-datepicker-datepicker.js (46:39) Cannot call a namespace ("moment").
> ...

![Screenshot (1029)](https://github.com/alirahimi818/livewire-persian-datepicker/assets/6697222/91d4a47a-0a9d-4906-ba78-306d6d6b75e4)

**Comment by alirahimi818** [comment]
> Hi When I try "npm run dev" everything is ok but when I build it ("npm run build"), these errors are displayed & dates of the calendar are not shown.
> 
> > resources/js/livewire-datepicker-datepicker.js (33:24) Cannot call a namespace ("moment").
> > resources/js/livewire-datepicker-datepicker.js (35:24) Cannot call a namespace ("moment").
> > resources/js/livewire-datepicker-datepicker.js (46:39) Cannot call a namespace ("moment").
> > ...

Hi Misagh,
You must use the following command to add moment js to your package list
```npm i moment```

**Comment by Misagh90** [comment]
I installed it but it still has the same problem and does not work

**Comment by alirahimi818** [comment]
Please check that the following package is installed:
```npm i jalali-moment
```
If both packages are installed and you still receive an error, maybe the difference in different versions of the package caused the problem.

**Comment by alirahimi818** [comment]
As a second solution, remove the moment package and install only the jalali-moment package (this package automatically installs the packages it needs)

**Comment by Misagh90** [comment]
I tried both ways, would you tell me which versions are the best?

**Comment by alirahimi818** [comment]
You installed moment alone and it caused the problem. I write the suggested values ​​below:

```
"devDependencies": {
        "@tailwindcss/forms": "^0.5.2",
        "@tailwindcss/typography": "^0.5.0",
        "autoprefixer": "^10.4.7",
        "axios": "^1.1.2",
        "laravel-mix": "^6.0.49",
        "postcss": "^8.4.14",
        "tailwindcss": "^3.1.0"
    },
    "dependencies": {
        "alpinejs": "^3.13.0",
        "fs": "^0.0.1-security",
        "jalali-moment": "^3.3.11",
        "material-icons": "^1.13.10",
        "moment-timezone": "^0.5.43",
        "os": "^0.1.2",
        "path": "^0.12.7",
    }
```

**Comment by alirahimi818** [comment]
I think I found your problem. There was a javascript issue with vite that has been fixed.
Please use version v1.1.5

**Comment by Misagh90** [comment]
Thank you
Now it is fixed and it works very well
